exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('characters').del()
    .then(function () {
      // Inserts seed entries
      return knex('characters').insert([
        {
          name: "Rick Sanchez",
          bio: "Rick Sanchez is the co-eponymous main character and leading protagonist of the show. He is a genius scientist whose alcoholism and reckless, nihilistic behavior are a source of concern for his daughter's family, as well as the safety of their son, Morty.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Rick_Sanchez.png',
          voteCount: 19,
          createdAt: new Date(2004, 4, 17),
        },
        {
          name: "Beth Smith",
          bio: "Beth Smith (née Sanchez) is the daughter of a deceased Rick Sanchez, (who was then replaced by a Rick from another dimension.), the ex-wife of Jerry Smith, and the mother of Summer Smith and a deceased Morty. Though, she currently acts as the mother of the Morty Smith and daughter to Rick Sanchez from the Dimension C-137. Sanctimonious and above others, she struggles with her husband over his contributions, due in part to his lower-level position, further driven by her father influencing her feelings of superiority.",
          voiceActor: 'Sarah Chalke',
          imageUrl: './images/Beth_Smith.png',
          voteCount: 7,
          createdAt: new Date(2011, 11, 11),
        },
        {
          name: "Jerry Smith",
          bio: "Jerry Smith is the ex-husband of Beth Smith and father to Summer Smith and, unknowingly, to a Morty Smith who died. Jerry always tries to think of the best interest of the family, but his attempt to be the patriarch of the family can often be misguided by his self-centered nature. This causes him a great deal of conflict with Rick, as his father-in-law clearly has no respect for him whatsoever.",
          voiceActor: 'Chris Parnell',
          imageUrl: './images/Jerry_Smith.png',
          voteCount: 0,
          createdAt: new Date(2013, 10, 16),
        },
        {
          name: "Morty Smith",
          bio: "Mortimer 'Morty' Smith Sr. is one of the two eponymous main protagonists in Rick and Morty. He is the grandson of Rick and is often forced to tag along on his various misadventures. Morty attends Harry Herpson High School along with his sister, Summer.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Morty_Smith.jpg',
          voteCount: 20,
          createdAt: new Date(2000, 11, 14),
        },
        {
          name: "Summer Smith",
          bio: "Summer Smith is the teenage daughter of Beth Smith, and Jerry Smith. She is the sister and granddaughter of her dimension's deceased Morty Smith, and Rick Sanchez. She is the only other member of the Smith Family to be aware of that fact.",
          voiceActor: 'Spencer Grammer',
          imageUrl: './images/Summer_is_cool.jpg',
          voteCount: 2,
          createdAt: new Date(2009, 10, 15),
        },
        {
          name: "Squanchy",
          bio: "Squanchy is a cat-like anthropomorphic creature that was invited to Rick and Summer's party in Ricksy Business. He is very good friends with Rick, sharing his love for alcohol. Morty and Jessica catch Squanchy engaging in auto-erotic asphyxiation masturbation in Morty's garage. He refers to this as 'squanching'.",
          voiceActor: 'Tom Kenny',
          imageUrl: './images/Squanchy_.png',
          voteCount: 10,
          createdAt: new Date(2002, 1, 14),
        },
        {
          name: "Mr. Meseeks",
          bio: "Mr. Meeseeks is the name of all the creatures summoned by activating a Meeseeks Box. Meeseeks are creatures created to serve a singular purpose for which they will go to any length to fulfill. After they serve their purpose, they expire and vanish into the air. Their motivation to help others comes from the fact that existence is painful to a Meeseeks, and the only way to be removed from existence is to complete the task they were called to perform.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/MeeseeksHQ.png',
          voteCount: 17,
          createdAt: new Date(2017, 3, 7),
        },
        {
          name: "Birdperson",
          bio: "Birdperson, currently known as Phoenixperson, is an old friend of Rick's, and has seemingly known Morty since he was a baby. He attends Rick's party looking for a new mate after ending his soul-bond with his previous spirit-partner. At the end of the episode, however, he gets back in the saddle with one of Summer's high school friends, Tammy.",
          voiceActor: 'Dan Harmon',
          imageUrl: './images/Birdperson.png',
          voteCount: 3,
          createdAt: new Date(2014, 8, 10),
        },
        {
          name: "Tammy Gueterman",
          bio: "Tammy Gueterman is a deep-cover agent for the Galactic Federation. She is also, possibly as a disguise, a student at Harry Herpson High School and a friend of Summer Smith. She became engaged to Birdperson and planned a wedding as a ploy to gather as many enemies of the Galactic Federation in one location in order to capture and arrest them. After the fall of the Federation, she became the leader of the remains, and will likely be the show's main villain.",
          voiceActor: 'Cassie Steele',
          imageUrl: './images/Tammy.png',
          voteCount: 1,
          createdAt: new Date(2012, 11, 22),
        },
        {
          name: "Baby Legs",
          bio: "Baby Legs is a detective on a murder mystery TV series in an alternate dimension that features him and a partner named Regular Legs. Baby Legs is a full-grown adult with the legs of a baby. He has a high-pitched, nasally voice.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Baby_Legs.png',
          voteCount: 6,
          createdAt: new Date(2016, 9, 14),
        },
        {
          name: "Mr. Poopybutthole",
          bio: "Mr. Poopybutthole is a long-time family friend of the Smiths. Rick clearly considers him to have long been a dependable person, although it's uncertain how long they've known each other. He made his first appearance in the episode Total Rickall. He is voiced by Justin Roiland.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Mr_poopy_butthole.png',
          voteCount: 9,
          createdAt: new Date(2011, 4, 29),
        },
        {
          name: "Ants in my Eyes Johnson",
          bio: "Ants in my Eyes Johnson is a store owner who appears in a commercial in Rixty Minutes for his electronics store.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Ants_in_my_eyes_johnson.png',
          voteCount: 12,
          createdAt: new Date(2001, 2, 15),
        },
        {
          name: "Abradolf Lincler",
          bio: "Abradolf Lincler is a humanoid experiment debuting in Ricksy Business. He was created when Rick combined the DNA of Abraham Lincoln and Adolf Hitler, in an attempt to create a morally neutral super leader. He failed and the end result was a cognitively dissonant and morally-confused emotional trainwreck.",
          voiceActor: 'Maurice LaMarche',
          imageUrl: './images/Abradolf_Lincler.jpg',
          voteCount: 6,
          createdAt: new Date(2011, 6, 19),
        },
        {
          name: "Brad",
          bio: "Brad is a recurring character in Rick and Morty and Jessica's ex-boyfriend. He is a student at Harry Herpson High School, along with Morty and Summer. He is shown to be a jock who plays basketball (and possibly other sports) for the high school.",
          voiceActor: 'Echo Kellum',
          imageUrl: './images/Brad.jpg',
          voteCount: 4,
          createdAt: new Date(2011, 2, 23),
        },
        {
          name: "Eyeholes Man",
          bio: "Eyeholes Man is a spandex-clad alien with a megaphone who lives to beat up anyone who is caught with the cereal 'Eyeholes'. He is featured in various commercials across the galaxy, as shown in the episode Interdimensional Cable 2: Tempting Fate. He claims that only he can have Eyeholes. Rick Sanchez tells Morty Smith not to be caught with a box of Eyeholes in his possession when the Eyeholes Man is around or else he'll start beating him up to get his box of Eyeholes back.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Eyeholes_Man.png',
          voteCount: 1,
          createdAt: new Date(2011, 3, 22),
        },
        {
          name: "Gazorpazorpfield",
          bio: "Gazorpazorpfield is the main character of a fictional in-series TV show of the same name. He is a parody of Garfield. He is identical to Garfield, only he is a lighter shade of orange, and has arms on his head in the place of ears, a common Gazorpian trait.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Gazorpazorpfield_Bitch.png',
          voteCount: 2,
          createdAt: new Date(2015, 6, 20),
        },
        {
          name: "Gene Vagina",
          bio: "Gene Vagina (no relation) is the principal of Harry Herpson High School. Principal Vagina seems to be incompetent in both his personal and professional life. He seems fully aware of the coincidence in his last name.",
          voiceActor: 'Phil Hendrie',
          imageUrl: './images/Principal_Vagina.png',
          voteCount: 16,
          createdAt: new Date(2014, 6, 20),
        },
        {
          name: "Scary Terry",
          bio: "Scary Terry is a character that appeared as the secondary antagonist in the episode 'Lawnmower Dog' and the comic story Morty and Rick in: Mortballs. After a failed attempt at killing them, Scary Terry retreats and heads home. While he is asleep, Rick and Morty incept his dreams and befriend him. He is known for saying 'bitch' at the end of almost every sentence.",
          voiceActor: 'Jess Harnell',
          imageUrl: './images/scary_terry.png',
          voteCount: 18,
          createdAt: new Date(2013, 6, 20),
        },
        {
          name: "Mr. Goldenfold",
          bio: "Mr. Goldenfold is Morty's eccentric math teacher. Not much is known about Mr. Goldenfold's history besides the fact that he is divorced. He has an apparent attraction to the television character Mrs. Pancakes, who he has romantic dreams about.",
          voiceActor: 'Brandon Johnson',
          imageUrl: './images/MrGoldenfold.png',
          voteCount: 8,
          createdAt: new Date(2015, 1, 20),
        },
        {
          name: "Snuffles(Snowball)",
          bio: "Snuffles, (who changed his name to Snowball and back again) was Morty's pet dog featured in the episode Lawnmower Dog. Snuffles is a small, fluffy white-haired dog that experiences some trouble with being potty-trained until Rick develops an IQ-enhancing helmet for him at the request of Jerry.",
          voiceActor: 'Rob Paulsen',
          imageUrl: './images/Snuffles-helmet.jpg',
          voteCount: 2,
          createdAt: new Date(2016, 10, 20),
        },
        {
          name: "Sleepy Gary",
          bio: "Sleepy Gary was a false character created by the Alien Parasites who invaded the Smith house. He passes himself off as a member of the immediate family, as well as Jerry's secret lover. Sleepy Gary, just like his name says, is usually very sleepy and spends most of his time, sleeping. Of all the alien parasites, he is the nicest and most convincing of all of them.",
          voiceActor: 'Matt Walsh',
          imageUrl: './images/Sleepy_Gary_Better_Image.png',
          voteCount: 4,
          createdAt: new Date(2013, 2, 20),
        },
        {
          name: "Mr. Lucius Needful",
          bio: "Mr. Lucius Needful, (also known as the Devil) is an eccentric gentleman who runs a vintage antique shop called Needful Things. He hires Summer to help work around the shop, but his merchandise curses people. Mr. Needful is shown to be dark and menacing, but treats Summer with respect. He receives joy in giving unsuspecting customers cursed items, and does his best to ensure he runs a successful business.",
          voiceActor: 'Alfred Molina',
          imageUrl: './images/Mr.Needful.png',
          voteCount: 6,
          createdAt: new Date(2014, 6, 20),
        },
        {
          name: "Tiny Rick",
          bio: "Tiny Rick is a younger version of Rick created through Operation Phoenix in the episode 'Big Trouble In Little Sanchez'. By transferring his brain into a younger clone of himself, Rick is able to attend Harry Herpson High School, along with Morty and Summer, in an effort to help catch a vampire within their school.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/TinyRick.png',
          voteCount: 2,
          createdAt: new Date(2013, 10, 10),
        },
        {
          name: "Tophat Jones",
          bio: "Tophat Jones is a breakfast cereal mascot that appears in a commercial for Strawberry Smiggles in the episode 'Rixty Minutes', and has since then made numerous appearances in Rick and Morty, along with the Strawberry Smiggles product itself. Jones is a parody of Lucky the Leprechaun, the mascot for Lucky Charms, and the Trix Rabbit, the mascot for Trix Cereal. Tophat Jones' selfishness and greed led to the dismemberment of his flesh and organs. It can be assumed that he wasn't a very good person outside from what we've seen of him either since he immediately saw demons during his near death experience.",
          voiceActor: 'Justin Roiland',
          imageUrl: './images/Tophatjones.png',
          voteCount: 6,
          createdAt: new Date(2009, 1, 27),
        },
        {
          name: "Armagheadon",
          bio: "Armagheadon is a Cromulon that appeared in the episode Get Schwifty. He is a giant apocalyptic head that confronted the people of Earth, trying to get them to make a hit song for them and then put them on his show, Planet Music. The majority of people in the world (led by Principal Vagina) misinterpreted him as a god and started the religion of Headism to worship him. His name is a pun on armegeddon.",
          voiceActor: 'Unknown',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/7/72/S2e5_Cromulon.png/revision/latest/scale-to-width-down/250?cb=20160926041704',
          voteCount: 23,
          createdAt: new Date(2000, 1, 27),
        },
        {
          name: "The President",
          bio: "The President is the president of the United States of America.  He is first encountered in the Pentagon (the lame one, here on Earth), where he is discussing the problem of the Cromulon with his aides. Rick and Morty entered the building and Rick explained that the Cromulon was actually requesting a live performance of a newly written song.",
          voiceActor: 'Keith David',
          imageUrl: 'https://vignette2.wikia.nocookie.net/rickandmorty/images/e/ea/President.png/revision/latest/scale-to-width-down/250?cb=20150829164829',
          voteCount: 5,
          createdAt: new Date(2015, 7, 27),
        },
        {
          name: "Annie",
          bio: "Annie is a member and only survivor of the team working on a theme park Anatomy Park that was being constructed inside the body of the homeless human Ruben. Annie was a member of Dr. Xenon Bloom's team and was apparently working at a churro stand in Anatomy Park. During their escape, she is the first to be suspected to be behind the failing security systems, until it is revealed that Poncho is the culprit. She later grows fond of Morty after he saves the group from Gonorrhea and attacks Poncho when he turns on the group.",
          voiceActor: 'Jackie Buscarino',
          imageUrl: 'https://vignette1.wikia.nocookie.net/rickandmorty/images/0/01/Annie.png/revision/latest/scale-to-width-down/250?cb=20160923152636',
          voteCount: 2,
          createdAt: new Date(2013, 7, 23),
        },
        {
          name: "Leonard Smith",
          bio: "Leonard Smith is Jerry's father, Joyce's husband, Summer and Morty's paternal grandfather. He appears in the episode 'Anatomy Park'. Like his wife, he is a swinger and participates in a three-way relationship with his wife and Jacob where he mainly participates as a voyeur. Leonard appears to be a very honest and open individual, which occasionally makes his son Jerry uncomfortable.",
          voiceActor: 'Dana Carvey',
          imageUrl: 'https://vignette4.wikia.nocookie.net/rickandmorty/images/7/74/Leonard_Smith.png/revision/latest/scale-to-width-down/250?cb=20140421044137',
          voteCount: 0,
          createdAt: new Date(2009, 3, 19),
        },
        {
          name: "Joyce Smith",
          bio: "Joyce Smith is Jerry's mother, Leonard's wife, and Morty's paternal grandmother. With his consent, she takes Jacob as a male consort due to her husband's impotence. Joyce made her first and only appearance in the episode Anatomy Park, where Jerry wanted to have a normal Christmas holiday and kept pushing his family to be normal for when his parents visited.",
          voiceActor: 'Patricia Lentz',
          imageUrl: 'https://vignette1.wikia.nocookie.net/rickandmorty/images/0/00/Joyce_in_Anatomy_Park.JPG/revision/latest/scale-to-width-down/250?cb=20140416061531',
          voteCount: 0,
          createdAt: new Date(2008, 3, 19),
        },
        {
          name: "Jessica",
          bio: "Jessica is a student at Harry Herpson High School. She is a popular girl in Morty's math class who he desires to be with romantically and often has surreal daydreams about, almost exclusively sexual in nature. Much to Morty's dismay she is already in a relationship with Brad, whom she frequently experiences difficulties with. She is voiced by Kari Wahlgren. Morty has an obvious crush on her, but Jessica doesn't acknowledge Morty frequently. So far, she has only spoken to him directly three times",
          voiceActor: 'Patricia Lentz',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/e/e8/Jessica.png/revision/latest/scale-to-width-down/250?cb=20150706222334',
          voteCount: 0,
          createdAt: new Date(2013, 1, 13),
        },
        {
          name: "Arthricia",
          bio: "Arthricia is an alien girl who lives on a distant planet that appeared in the episode Look Who's Purging Now. She is a nice little Amish girl who appears to be some kind of a cat-like human. She doesn't agree with the yearly purges, in which her planet's society has and fights every year to survive during them. Arthricia holds strong political beliefs and a huge grudge on her society for the pain it put her through all her life with its yearly purges. She will go to many lengths to make sure they repay their debts, and in the end, she ends up killing them, with no hesitation. She is however a quick but irrational thinker.",
          voiceActor: 'Chelsea Kane',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/3/31/Arthricia_end_HQ.png/revision/latest/scale-to-width-down/250?cb=20150930225041',
          voteCount: 0,
          createdAt: new Date(2015, 1, 10),
        },
        {
          name: "Blim Blam",
          bio: "Blim Blam is a Korblock murderer who eats babies, and apparently traveled to Earth to do so. He was eventually captured and chained up by Rick in an attempt to cure Blim Blam's 'space AIDS' in order to become rich selling the cure. He was discovered by Beth and Jerry, however, and the two's bickering annoyed Blim Blam to the point that he broke free, berated the two by using a translation device Rick had (as he could only speak in alien beforehand), and then left promising never to return to Earth. Blim Blam's race is biologically incapable of laughter.",
          voiceActor: 'Unknown',
          imageUrl: 'https://vignette4.wikia.nocookie.net/rickandmorty/images/e/ec/Blim_Blam.png/revision/latest/scale-to-width-down/250?cb=20160923081159',
          voteCount: 0,
          createdAt: new Date(2015, 4, 10),
        },
        {
          name: "Cousin Nicky",
          bio: "Cousin Nicky was a minor character that appears in the episode Total Rickall. In a flashback scene, he is shown saving the Smith family and Mr. Poopybutthole from within a broken elevator after they see the Hulk Musical. He was also present when the family was captured by a Nazi while on board a Nazi submarine until they are saved by Mr. Beauregard. Like many of the other characters within the episode, he is a persona taken by the Alien Parasites. Rick Sanchez deduces pretty quickly that Cousin Nicky might be a parasite, and shoots him in the shoulder early in the episode. It is unknown whose cousin he is supposed to be, although due to his age he was mostly likely created as Beth or Jerry's cousin.",
          voiceActor: 'Ryan Ridley',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/f/fa/Cousin_Nicky.png/revision/latest/scale-to-width-down/250?cb=20170131021340',
          voteCount: 3,
          createdAt: new Date(2014, 4, 10),
        },
        {
          name: "Prince Nebulon",
          bio: "Prince Nebulon was the leader of the Zigerions in Rick and Morty. He appears as the main antagonist in M. Night Shaym-Aliens!. He has a long-standing grudge against Rick and is committed to stealing the recipe for concentrated dark matter from him. He drafts a plan to abduct Rick into a simulated reality in order to trick him into giving up the formula. He employs Kevin to research human nudity in order to create a convincing Morty to help bring Rick's guard down. Despite putting Rick through several layers of simulations, he was tricked by Rick into blowing up the entire Zigerion spaceship.",
          voiceActor: 'David Cross',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/8/8b/PrinceNebulon.png/revision/latest/scale-to-width-down/250?cb=20140115215419',
          voteCount: 2,
          createdAt: new Date(2013, 4, 10),
        },
        {
          name: "Davin",
          bio: "Davin was Beth's coworker at St. Equis Hospital. Davin is in love with Beth and he constantly hits on her and tries to seduce her and win her over. Because of this, Jerry is extremely jealous of him. Beth denies having any feelings for him, which she most likely doesn't, but Jerry does not trust her around him and absolutely hates him with every fiber in his being.",
          voiceActor: 'Dan Harmon',
          imageUrl: 'https://vignette2.wikia.nocookie.net/rickandmorty/images/f/f9/Davin2.png/revision/latest/scale-to-width-down/250?cb=20140516044315',
          voteCount: 6,
          createdAt: new Date(2012, 4, 10),
        },
        {
          name: "Dr. Xenon Bloom",
          bio: "Dr. Xenon Bloom is a character of the day and served as one of the protagonists, appearing in the 3rd episode, Anatomy Park. Bloom is an amoeba who is the co-founder of Anatomy Park. He is based on John Hammond, the creator and CEO of Jurassic Park.",
          voiceActor: 'John Oliver',
          imageUrl: 'https://vignette4.wikia.nocookie.net/rickandmorty/images/0/0b/Dr._Xenon_Bloom_HQ/revision/latest/scale-to-width-down/250?cb=20150930231812',
          voteCount: 0,
          createdAt: new Date(2009, 4, 10),
        },
        {
          name: "Ethan",
          bio: "Ethan is Summer's ex-boyfriend. He first appears in the episode 'Anatomy Park'. Ethan's relationship with Summer is kept secret until he barges in and confronts Summer about not answering his texts. Ethan is shown to be somewhat clingy, and deals with his own mess of insecurities, which Jacob helps him admit during the Smith's Christmas.",
          voiceActor: 'Daniel Benson',
          imageUrl: 'https://vignette1.wikia.nocookie.net/rickandmorty/images/0/0f/Ethan.png/revision/latest/scale-to-width-down/250?cb=20160913193848',
          voteCount: 0,
          createdAt: new Date(2008, 4, 10),
        },
        {
          name: "Fart",
          bio: "Fart is the name given to an unnamed gaseous being who appeared in the episode 'Mortynight Run'. Although technically nameless, it took on the name 'Fart' for convenience after Rick insulted it. It communicates through telepathy. Fart was a life form from another dimension that was being held captive and ordered to be assassinated by Krombopulos Michael. With the ability to alter the composition of atoms, Fart could produce any element from any atom by adding or removing protons, making him incredibly valuable to anyone who captured him.",
          voiceActor: 'Jemaine Clement',
          imageUrl: 'https://vignette1.wikia.nocookie.net/rickandmorty/images/8/84/Fart.jpg/revision/latest/scale-to-width-down/250?cb=20150806021947',
          voteCount: 0,
          createdAt: new Date(2007, 4, 10),
        },
        {
          name: "General Nathan",
          bio: "General Nathan was an American army general who appeared in the episode Get Schwifty. He wanted to destroy the Cromulons with nuclear weapons, but the President disagreed. He rebelled against the President and knocked him out, only for his plan to destroy them to fail. He is killed by Rick's particle beam wristwatch when he attempts to murder the President.",
          voiceActor: 'Kurtwood Smith',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/c/cb/Nathan.png/revision/latest/scale-to-width-down/250?cb=20150829164850',
          voteCount: 0,
          createdAt: new Date(2006, 4, 10),
        },
        {
          name: "Ice-T",
          bio: "Ice-T (also known as Tracy Lauren Marrow), is a well-known human rapper on Earth, who is actually an ageless wandering alien from the dawn of time known as Water-T. In his natural form, Water-T is a large capital T composed entirely of water. Before his return to Alphabetrium he was long imprisoned in the form of a spike of ice and took the name Ice-T. His Ice-T form was shown to be spectacularly resistant, deflecting a blast from a plasma ray strong enough to annihilate the earth. This durability might explain why he survived the catastrophe at the Grammys. Ice-T was also an impressive shapeshifter, which he used to blend into the worlds he inhabited along his travels.",
          voiceActor: 'Dan Harmon',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/2/26/Ice-T.PNG/revision/latest/scale-to-width-down/250?cb=20150902072346',
          voteCount: 0,
          createdAt: new Date(2006, 4, 10),
        },
        {
          name: "Jon",
          bio: "Jon is a parody on the character of the same name from the Garfield comics. He is a character on the Gazorpazorp's TV Show, Gazorpazorpfield. Jon is the owner of Gazorpazorpfield.",
          voiceActor: 'Tom Kenny',
          imageUrl: 'https://vignette4.wikia.nocookie.net/rickandmorty/images/3/37/Jon.png/revision/latest/scale-to-width-down/250?cb=20160604235033',
          voteCount: 0,
          createdAt: new Date(2006, 4, 10),
        },
        {
          name: "Jan Michael Vincent",
          bio: "Jan Michael Vincent is an actor who appeared in Interdimensional Cable 2: Tempting Fate. Eight versions of him appeared in the movie Jan Quadrant Vincent 16. Based on the trailer for the movie, it appeared to be an action movie set in a dystopian society where Jan Michael Vincents helped to maintain order.",
          voiceActor: 'Justin Roiland',
          imageUrl: 'https://vignette4.wikia.nocookie.net/rickandmorty/images/0/07/S2e8_Jan.png/revision/latest/scale-to-width-down/250?cb=20160605042002',
          voteCount: 0,
          createdAt: new Date(2006, 4, 10),
        },
        {
          name: "King Flippy Nips",
          bio: "King Flippy Nips is the ruler of Pluto. He first appeared in 'Something Ricked This Way Comes' as a secondary antagonist. He acts quite self-centered. he is also selfish because he knows everything his son says is real, but keeps quiet about it because he wants to stay king. He is also highly manipulative.",
          voiceActor: 'Richard Fulcher',
          imageUrl: 'https://vignette4.wikia.nocookie.net/rickandmorty/images/6/62/King_Flippynips.png/revision/latest/scale-to-width-down/250?cb=20140516021959',
          voteCount: 0,
          createdAt: new Date(2009, 7, 10),
        },
        {
          name: "King Jellybean",
          bio: "King Jellybean (also referred to as Mr. Jellybean) was a character featured in Meeseeks and Destroy. King Jellybean is a giant anthropomorphic jelly bean with the appearance of a male in his late forties to early sixties. He was revealed at the end of the episode that he was king of the poor village Rick and Morty tried to help. He was shortly thereafter killed by Rick, most likely as retaliation for Mr. Jellybean's actions against Morty. He has a kind and friendly appearance (which lures his victims in) which masks his true nature. He is assumed to have raped many boys because of his position as a kindly monarch (his memorial statue depicts him with a child).",
          voiceActor: 'Tom Kenny',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/f/fb/King_Jellybean.png/revision/latest/scale-to-width-down/250?cb=20160923152857',
          voteCount: 0,
          createdAt: new Date(2010, 9, 10),
        },
        {
          name: "Krombopulos Michael",
          bio: "Krombopulos Michael was a Gromflomite assassin that purchased weapons from Rick Sanchez. Rick refers to him as his best customer.[1] His final purchase was an anti-matter handgun, to be used to kill a gaseous target that couldn't be destroyed with normal weapons. When he meets Rick at a garage to purchase the gun, Krombopulos introduces himself to Morty, giving him a business card.",
          voiceActor: 'Andy Daly',
          imageUrl: 'https://vignette4.wikia.nocookie.net/rickandmorty/images/9/93/Krombopulos_Michael.png/revision/latest/scale-to-width-down/250?cb=20160919070008',
          voteCount: 0,
          createdAt: new Date(2011, 2, 10),
        },
        {
          name: "Lucy",
          bio: "Lucy is a character who appeared in the episode 'Ricksy Business', serving as the main antagonist. She worked as a maid on the Titanic 2. While coming off as a sweet lady, she eventually becomes obsessed with Jerry; attempting to force him to have sex with her at gunpoint.",
          voiceActor: 'Alejandra Gollas',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/4/47/Lucy.JPG/revision/latest/scale-to-width-down/250?cb=20140415064550',
          voteCount: 0,
          createdAt: new Date(2010, 3, 19),
        },
        {
          name: "Mrs. Pancakes",
          bio: "Mrs. Pancakes is a character from an in-universe TV show called The Days and Nights of Mrs. Pancakes. Mr. Goldenfold has a celebrity crush on her. He oftentimes dreams of being with her. Rick stated that he also watches the show, but was a full season behind at the time.",
          voiceActor: 'Melique Berger',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/b/bd/Mrs._Pancakes_Picture.png/revision/latest/scale-to-width-down/250?cb=20170127151948',
          voteCount: 0,
          createdAt: new Date(2011, 1, 19),
        },
        {
          name: "Randy Dicknose",
          bio: "Randy Dicknose is a host on the new hit show MAN vs. CAR. He is seen on a television programme from one of infinite dimensions. His co-host Michael McLick remains quiet through the segment, leaving him to carry on with the segment by himself. As the car defeats the man, he starts laughing, stating how the cars always win.",
          voiceActor: 'Justin Roiland',
          imageUrl: 'https://vignette2.wikia.nocookie.net/rickandmorty/images/a/a8/Randy_Dicknose.png/revision/latest/scale-to-width-down/250?cb=20151211221935',
          voteCount: 0,
          createdAt: new Date(2013, 4, 10),
        },
        {
          name: "Revolio Clockberg Jr.",
          bio: "Revolio Clockberg Jr., also referred to as Gearhead, is a recurring character who first appeared in the episode Ricksy Business. His character is a representative of 'social gearheads', people who know a lot of technical information about gears. In Gearhead's case, it's information about the Gear Wars and engineering. He is a guest at Rick and Summer's party and can play an instrument similar to a lute. ",
          voiceActor: 'Scott Chernoff',
          imageUrl: 'https://vignette2.wikia.nocookie.net/rickandmorty/images/7/7d/Gearheadtransparent.png/revision/latest/scale-to-width-down/250?cb=20160901012718',
          voteCount: 0,
          createdAt: new Date(2013, 9, 13),
        },
        {
          name: "Doofus Rick",
          bio: "Doofus Rick from dimension J19ζ7 is the least respected of all the Ricks. Doofus Rick is the kindest and gentlest of all the Ricks. He approached Jerry during the investigation at the Smith house and engaged him in conversation, expressing genuine interest in Jerry's life and abilities. Perhaps because they were both ostracized and mocked by the rest of the Ricks present, the two quickly bonded.",
          voiceActor: 'Justin Roiland',
          imageUrl: 'https://vignette1.wikia.nocookie.net/rickandmorty/images/d/dd/S1e10_doofy.png/revision/latest/scale-to-width-down/250?cb=20160911021823',
          voteCount: 0,
          createdAt: new Date(2014, 9, 2),
        },
        {
          name: "Stealy",
          bio: "Stealy is a character seen in 'Interdimensional Cable 2: Tempting Fate'. He stars in The Adventures of Stealy, a TV series where he goes through a location stealing numerous items and determining their value. The Plumbus was introduced in 'The Adventures of Stealy'.",
          voiceActor: 'Justin Roiland',
          imageUrl: 'https://vignette3.wikia.nocookie.net/rickandmorty/images/7/78/Stealy.jpg/revision/latest/scale-to-width-down/250?cb=20160609132837',
          voteCount: 0,
          createdAt: new Date(2015, 9, 10),
        },
        {
          name: "Unity",
          bio: "Unity is a collective hivemind and Rick Sanchez's former lover. It is a powerful entity that can control minds, and form alliances. It takes the forms of multiple genders, races, and likely species, but uses both male and female avatars, including around Rick. Unity assimilates minds by making one of its hosts vomit into another individual's mouth in a terrifying and disgusting fashion, effectively assimilating the individual into the hivemind.",
          voiceActor: 'Christina Hendricks',
          imageUrl: 'https://vignette1.wikia.nocookie.net/rickandmorty/images/4/45/Unity_Assimilation.png/revision/latest/scale-to-width-down/250?cb=20160923075643',
          voteCount: 0,
          createdAt: new Date(2014, 9, 19),
        },
        {
          name: "Zeep Xanflorp",
          bio: "Zeep Xanflorp is a scientist within Rick's Microverse Battery who creates his own micro-planet power supply called the Miniverse. His development of a new power supply prevents Rick from using his flying car. Zeep is depicted as arrogant and very intelligent, and in many ways a parallel of Rick Sanchez.",
          voiceActor: 'Stephen Colbert',
          imageUrl: 'https://vignette1.wikia.nocookie.net/rickandmorty/images/1/16/Zeep.png/revision/latest/scale-to-width-down/250?cb=20150901180927',
          voteCount: 0,
          createdAt: new Date(2015, 2, 19),
        },

      ]);
    });
};
